---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: portall
    sources:
      stages:
        - dev
  - origin:
      kind: Warehouse
      name: portall-git
    sources:
      stages:
        - dev
  promotionTemplate:
    spec:
      vars:
        - name: envPath
          value: helm/portall/prod-roldyx
        - name: stage
          value: prod-roldyx
        - name: argocdApp
          value: portall-europe-prod-roldyx
      steps:
      - task:
          name: promote
        as: promote-to-prod
