---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: portall
spec:
  interval: 1m
  subscriptions:
  - image:
      repoURL: registry.softonic.io/portall/web
      imageSelectionStrategy: SemVer
      discoveryLimit: 5
      strictSemvers: true
