apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kargo.akuity.io/authorized-stage: kargo-helm:prod-asia
  labels:
    softonic.io/group: tooling
    softonic.io/service: portall
    softonic.io/site: global
  name: portall-asia
  namespace: argocd
spec:
  destination:
    namespace: portall
    server: https://34.124.152.152
  project: portall
  source:
    path: ./stages/prod
    repoURL: git@github.com:softonic-development/portall-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
