---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry.softonic.io
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: project-coreops-id
  target:
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: image
    name: registry.softonic.io
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kargo-helm-registry-softonic-io
