apiVersion: v1
data:
  password: eHRlY2guLi4x
  repoURL: aHR0cHM6Ly9naXRodWIuY29tL3NvZnRvbmljLWRldmVsb3BtZW50L2thcmdvLWhlbG0uZ2l0
  username: cm9sZHl4b3JpZ2luYWw=
kind: Secret
metadata:
  creationTimestamp: "2025-06-18T14:59:18Z"
  labels:
    kargo.akuity.io/cred-type: git
  name: github-creds
  namespace: kargo-helm
  resourceVersion: "7471535865"
  uid: ef0976e9-66ce-4678-a445-012ed77205a1
type: Opaque
