---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-helm
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
  - stageSelector:
      name: staging
    autoPromotionEnabled: false
  - stageSelector:
      name: prod
    autoPromotionEnabled: false
