---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: portall
  namespace: kargo-helm
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/softonic-development/portall-manifests
      branch: main
      commitSelectionStrategy: SemVer
      allowTags: '^\d+\.\d+\.\d+$'
      semverConstraint: '>= 1.1.0'
      discoveryLimit: 5
  - image:
      repoURL: registry.softonic.io/portall/web
      imageSelectionStrategy: SemVer
      discoveryLimit: 5
