---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: features
    sources:
      stages:
        - dev
  - origin:
      kind: Warehouse
      name: portall
    sources:
      stages:
        - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: image
          value: registry.softonic.io/portall/web
        - name: repoURL
          value: https://github.com/softonic-development/kargo-helm.git
        - name: envPath
          value: env/staging
        - name: argocdApp
          value: kargo-helm-staging

